### ISSUE TITLE
Is there anyway to automatically perform checks in background?

### ISSUE THREAD

**Issue by tural-ali** [yii2tech/selfupdate#1]
First of all, thank you for such a great tools.

I don't get this extensions need so much because all this operations can be done using simple crontab commands. What makes this addon different? 

Is there anyway to perform checks for git changes automatically and whenever it detects that there is something new then it updates whole project automatically.

**Comment by klimov-paul** [comment]
> Is there anyway to perform checks for git changes automatically and whenever it detects that there is something new then it updates whole project automatically.

It does exactly the same. Place 'self-update' to your crontab and it will update project only if there were any changes in the central repo.

**Comment by tural-ali** [comment]
and how frequent to do it?
will it composer update also?

**Comment by klimov-paul** [comment]
> and how frequent to do it?

It is up to you: once a day or every 15 minutes - it is your choice.

> will it composer update also?

It will on certain conditions. See https://github.com/yii2tech/selfupdate#self-update-workflow
