### ISSUE TITLE
Failed to instantiate mutex

### ISSUE THREAD

**Issue by mysoundmagic** [yii2tech/selfupdate#6]
i got error 'Failed to instantiate component or class "mutex".' in /var/www/html/myApp.dev/vendor/yiisoft/yii2/di/Instance.php:134

how to solve that error ?

**Comment by klimov-paul** [comment]
You should configure `mutex` component in your console application or at `SelfUpdateController::$mutex`
https://github.com/yii2tech/selfupdate/blob/master/SelfUpdateController.php#L61

**Comment by mysoundmagic** [comment]
ok thank you solve.

i'm so sorry out of topic from this issue. allow me one question, is this extension will automatic update from git or i still have to execute command from terminal ?

**Comment by klimov-paul** [comment]
https://github.com/yii2tech/selfupdate#self-update-workflow

**Comment by mysoundmagic** [comment]
thank you
